const dummyHeatmap = [
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.29,
      locationY: 16.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 72.57,
      locationY: 50.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 51.52,
      locationY: 51.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 58.19,
      locationY: 71.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x-",
      locationX: 48.67,
      locationY: 72.44,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x-",
      locationX: 48.67,
      locationY: 72.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 24.95,
      locationY: 26.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 37.33,
      locationY: 54.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 37.24,
      locationY: 88.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 73.43,
      locationY: 17.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 73.33,
      locationY: 71.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 65.81,
      locationY: 13.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x+",
      locationX: 48.57,
      locationY: 15.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "N+",
      locationX: 54.76,
      locationY: 20.22,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.48,
      locationY: 51.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 76.57,
      locationY: 50.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 63.33,
      locationY: 48.67,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 61.43,
      locationY: 90.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x-",
      locationX: 48.57,
      locationY: 79.11,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 85.14,
      locationY: 34.0,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 24.57,
      locationY: 18.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 43.24,
      locationY: 39.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 43.71,
      locationY: 31.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "c",
      locationX: 66.1,
      locationY: 48.22,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.0,
      locationY: 66.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 75.81,
      locationY: 49.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 59.62,
      locationY: 25.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 62.67,
      locationY: 85.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 40.19,
      locationY: 70.0,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 45.24,
      locationY: 80.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 33.9,
      locationY: 83.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d-",
      locationX: 75.52,
      locationY: 81.78,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 13.81,
      locationY: 70.67,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 75.24,
      locationY: 50.67,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 55.43,
      locationY: 48.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 61.62,
      locationY: 82.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x+",
      locationX: 48.29,
      locationY: 76.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "N+",
      locationX: 59.9,
      locationY: 56.22,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.1,
      locationY: 53.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 78.29,
      locationY: 81.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 62.0,
      locationY: 49.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 66.48,
      locationY: 12.0,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "c",
      locationX: 19.81,
      locationY: 78.67,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a/",
      locationX: 84.76,
      locationY: 65.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "z",
      locationX: 10.29,
      locationY: 31.56,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.67,
      locationY: 75.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 75.05,
      locationY: 51.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 51.81,
      locationY: 49.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q/",
      locationX: 61.62,
      locationY: 91.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "z",
      locationX: 37.52,
      locationY: 6.22,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.0,
      locationY: 75.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 75.9,
      locationY: 18.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 57.05,
      locationY: 49.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 59.71,
      locationY: 66.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 24.95,
      locationY: 57.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 28.19,
      locationY: 44.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 33.71,
      locationY: 87.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 63.24,
      locationY: 68.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 72.48,
      locationY: 64.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 66.0,
      locationY: 14.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 48.76,
      locationY: 20.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 19.05,
      locationY: 79.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 34.0,
      locationY: 50.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 32.95,
      locationY: 88.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "x-",
      locationX: 51.24,
      locationY: 81.11,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.57,
      locationY: 78.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 76.57,
      locationY: 47.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 62.29,
      locationY: 36.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 58.86,
      locationY: 89.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x+",
      locationX: 48.19,
      locationY: 79.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "N+",
      locationX: 67.43,
      locationY: 23.33,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 13.52,
      locationY: 76.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 77.71,
      locationY: 48.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 47.9,
      locationY: 48.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 46.1,
      locationY: 67.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 33.52,
      locationY: 85.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "x+",
      locationX: 52.67,
      locationY: 76.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "N+",
      locationX: 46.48,
      locationY: 78.44,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 85.14,
      locationY: 18.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 27.14,
      locationY: 22.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 38.19,
      locationY: 59.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 32.76,
      locationY: 88.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "c",
      locationX: 68.19,
      locationY: 14.67,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.48,
      locationY: 81.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 74.76,
      locationY: 17.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s/",
      locationX: 60.19,
      locationY: 34.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "삼성화재",
      mainAction: "z",
      locationX: -1.0,
      locationY: -1.0,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 15.43,
      locationY: 78.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 72.29,
      locationY: 49.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 54.29,
      locationY: 48.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 57.62,
      locationY: 10.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x-",
      locationX: 48.19,
      locationY: 16.0,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 84.67,
      locationY: 79.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 25.24,
      locationY: 23.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 43.05,
      locationY: 49.11,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 37.9,
      locationY: 88.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "x+",
      locationX: 51.52,
      locationY: 68.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "N+",
      locationX: 31.14,
      locationY: 20.67,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 84.57,
      locationY: 79.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 27.33,
      locationY: 40.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 47.81,
      locationY: 66.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 40.57,
      locationY: 14.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "c",
      locationX: 73.05,
      locationY: 76.0,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.1,
      locationY: 18.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 77.05,
      locationY: 50.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 51.14,
      locationY: 50.67,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 58.67,
      locationY: 13.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 48.67,
      locationY: 17.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 34.0,
      locationY: 22.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 8.29,
      locationY: 48.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "v",
      locationX: 15.24,
      locationY: 50.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 77.33,
      locationY: 47.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 52.76,
      locationY: 35.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 53.33,
      locationY: 52.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 47.71,
      locationY: 50.67,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 68.38,
      locationY: 49.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 54.57,
      locationY: 35.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 57.52,
      locationY: 90.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x-",
      locationX: 48.57,
      locationY: 81.33,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 84.76,
      locationY: 35.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 25.52,
      locationY: 69.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 41.24,
      locationY: 56.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 33.43,
      locationY: 44.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d-",
      locationX: 73.71,
      locationY: 64.67,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 13.9,
      locationY: 17.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 75.24,
      locationY: 72.67,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 53.71,
      locationY: 37.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 60.29,
      locationY: 9.11,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "c",
      locationX: 19.24,
      locationY: 41.56,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 85.24,
      locationY: 26.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 23.24,
      locationY: 77.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 40.0,
      locationY: 57.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 38.19,
      locationY: 89.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "c",
      locationX: 74.76,
      locationY: 68.22,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 14.86,
      locationY: 56.67,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 75.71,
      locationY: 51.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 70.0,
      locationY: 33.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "v",
      locationX: 67.24,
      locationY: 44.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 34.1,
      locationY: 73.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 47.33,
      locationY: 72.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 47.71,
      locationY: 49.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 68.38,
      locationY: 19.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 63.43,
      locationY: 39.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 66.0,
      locationY: 68.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "c",
      locationX: 19.43,
      locationY: 19.78,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 85.9,
      locationY: 28.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 28.57,
      locationY: 44.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 37.33,
      locationY: 53.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 41.24,
      locationY: 13.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "c",
      locationX: 74.48,
      locationY: 54.22,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a/",
      locationX: 13.52,
      locationY: 68.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "z",
      locationX: 51.81,
      locationY: 54.89,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 85.81,
      locationY: 64.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 25.33,
      locationY: 52.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 48.38,
      locationY: 20.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 48.1,
      locationY: 33.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "x",
      locationX: 51.62,
      locationY: 25.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 37.24,
      locationY: 69.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 38.76,
      locationY: 51.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 33.43,
      locationY: 48.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 76.29,
      locationY: 49.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 68.29,
      locationY: 73.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 60.1,
      locationY: 89.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 49.05,
      locationY: 80.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 67.14,
      locationY: 49.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 72.76,
      locationY: 15.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 54.48,
      locationY: 78.0,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 48.19,
      locationY: 66.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 52.0,
      locationY: 51.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 70.29,
      locationY: 46.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q/",
      locationX: 62.19,
      locationY: 84.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "z",
      locationX: 26.67,
      locationY: 7.56,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 12.29,
      locationY: 75.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 74.29,
      locationY: 18.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 68.0,
      locationY: 18.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 58.0,
      locationY: 91.11,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 47.9,
      locationY: 74.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 61.71,
      locationY: 66.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 62.57,
      locationY: 24.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 59.14,
      locationY: 83.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x+",
      locationX: 48.76,
      locationY: 65.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "N+",
      locationX: 58.76,
      locationY: 49.56,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 13.24,
      locationY: 77.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 77.62,
      locationY: 48.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 57.24,
      locationY: 55.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 59.62,
      locationY: 90.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 47.71,
      locationY: 74.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 59.33,
      locationY: 25.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 65.62,
      locationY: 51.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 57.14,
      locationY: 85.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "c",
      locationX: 24.76,
      locationY: 79.78,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 86.1,
      locationY: 22.0,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 27.52,
      locationY: 18.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 47.81,
      locationY: 39.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 42.76,
      locationY: 13.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "x+",
      locationX: 52.29,
      locationY: 16.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "N+",
      locationX: 34.57,
      locationY: 34.44,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 87.43,
      locationY: 22.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 28.1,
      locationY: 44.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 46.38,
      locationY: 61.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 33.14,
      locationY: 82.67,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "c",
      locationX: 74.1,
      locationY: 16.44,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 13.62,
      locationY: 79.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 72.95,
      locationY: 16.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 51.71,
      locationY: 29.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 53.05,
      locationY: 49.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 48.19,
      locationY: 50.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 55.71,
      locationY: 85.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 66.57,
      locationY: 63.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 58.76,
      locationY: 86.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 48.38,
      locationY: 74.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 37.52,
      locationY: 69.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 37.33,
      locationY: 50.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 37.33,
      locationY: 86.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "x",
      locationX: 51.62,
      locationY: 76.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 76.0,
      locationY: 21.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 70.48,
      locationY: 28.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 57.81,
      locationY: 89.11,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 48.29,
      locationY: 78.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 65.52,
      locationY: 79.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 56.38,
      locationY: 50.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 66.1,
      locationY: 54.67,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 24.57,
      locationY: 66.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 11.43,
      locationY: 96.0,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 35.14,
      locationY: 42.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 74.29,
      locationY: 28.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 56.48,
      locationY: 43.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 52.19,
      locationY: 62.0,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x",
      locationX: 48.38,
      locationY: 61.11,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "d",
      locationX: 37.24,
      locationY: 74.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 37.9,
      locationY: 53.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 35.52,
      locationY: 90.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "x-",
      locationX: 51.62,
      locationY: 82.44,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 13.33,
      locationY: 79.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 74.1,
      locationY: 20.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s/",
      locationX: 62.67,
      locationY: 60.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "삼성화재",
      mainAction: "z",
      locationX: -1.0,
      locationY: -1.0,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 13.81,
      locationY: 79.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 72.1,
      locationY: 17.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 52.57,
      locationY: 27.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 59.24,
      locationY: 89.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "c",
      locationX: 32.86,
      locationY: 24.67,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a/",
      locationX: 85.81,
      locationY: 25.11,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "z",
      locationX: 48.38,
      locationY: 30.67,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a/",
      locationX: 13.71,
      locationY: 24.44,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "z",
      locationX: 52.1,
      locationY: 45.11,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a/",
      locationX: 85.71,
      locationY: 71.78,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "z",
      locationX: 14.29,
      locationY: 28.22,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a/",
      locationX: 14.38,
      locationY: 75.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "z",
      locationX: 84.48,
      locationY: 70.0,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 85.62,
      locationY: 50.89,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 23.71,
      locationY: 20.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 33.24,
      locationY: 36.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q",
      locationX: 37.52,
      locationY: 13.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "x",
      locationX: 52.0,
      locationY: 18.0,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d",
      locationX: 74.86,
      locationY: 54.22,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 75.71,
      locationY: 7.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 61.05,
      locationY: 77.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "c",
      locationX: 30.29,
      locationY: 12.44,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 86.19,
      locationY: 26.0,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 24.76,
      locationY: 57.11,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 38.67,
      locationY: 49.11,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 40.57,
      locationY: 15.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "x-",
      locationX: 52.38,
      locationY: 17.56,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 13.81,
      locationY: 53.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 73.05,
      locationY: 77.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 88.86,
      locationY: 49.11,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q",
      locationX: 68.95,
      locationY: 18.0,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x+",
      locationX: 48.67,
      locationY: 17.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "N+",
      locationX: 52.57,
      locationY: 24.0,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a+",
      locationX: 13.14,
      locationY: 55.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f-",
      locationX: 76.1,
      locationY: 13.56,
    },
  ],
  [
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "a",
      locationX: 13.9,
      locationY: 53.56,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "f",
      locationX: 78.19,
      locationY: 36.89,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "s",
      locationX: 58.0,
      locationY: 45.78,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "q+",
      locationX: 67.14,
      locationY: 15.56,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "x-",
      locationX: 48.48,
      locationY: 16.89,
    },
  ],
  [
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "a",
      locationX: 86.57,
      locationY: 19.33,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "f",
      locationX: 26.67,
      locationY: 66.22,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "s",
      locationX: 47.62,
      locationY: 54.44,
    },
    {
      teamId: "KRPMAM01",
      teamName: "우리카드",
      mainAction: "q+",
      locationX: 42.57,
      locationY: 51.33,
    },
    {
      teamId: "KRPMEQ01",
      teamName: "삼성화재",
      mainAction: "d-",
      locationX: 56.76,
      locationY: 52.0,
    },
  ],
];

let dummyArr = [];
dummyHeatmap.forEach(i => {
  i.forEach(j => {
    // if (j.mainAction.includes("a"))
    dummyArr.push({
      locationX: j.locationX,
      locationY: j.locationY,
      mainAction: j.mainAction,
      color: "blue",
    });
  });
});

export default dummyHeatmap;
